/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function listFiles(dirPath: string, recursive: boolean, limit: number): Array<string>
export declare function benchmarkFileScan(dirPath: string, recursive: boolean, limit: number): BenchmarkResult
export interface BenchmarkResult {
  fileCount: number
  durationMs: number
}
